// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NicolasRecaldeEvaluacionProgreso1.Migrations
{
    [DbContext(typeof(NicolasRecaldeEvaluacionProgreso1ContextSQLServer))]
    [Migration("20250428131353_NicolasRecalde")]
    partial class NicolasRecalde
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NicolasRecaldeEvaluacionProgreso1.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("EsMayorEdad")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Salario")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("NicolasRecaldeEvaluacionProgreso1.Models.Plan_de_recompensas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Plan_de_recompensas");
                });

            modelBuilder.Entity("NicolasRecaldeEvaluacionProgreso1.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Clientes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Entrada")
                        .HasColumnType("date");

                    b.Property<string>("Informacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<DateOnly>("Salida")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Clientes");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("NicolasRecaldeEvaluacionProgreso1.Models.Plan_de_recompensas", b =>
                {
                    b.HasOne("NicolasRecaldeEvaluacionProgreso1.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("NicolasRecaldeEvaluacionProgreso1.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId");

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("NicolasRecaldeEvaluacionProgreso1.Models.Reserva", b =>
                {
                    b.HasOne("NicolasRecaldeEvaluacionProgreso1.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clientes");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
